huh:
    encore:
        entries:
            - { name: contao-multifileupload-bundle, file: 'vendor/heimrichhannot/contao-multifileupload-bundle/src/Resources/assets/js/contao-multifileupload-bundle.js', requiresCss: true }
        legacy:
            js:
              - multifileupload
              - dropzone
            css:
              - dropzone