services:
  _defaults:
    autowire: true

  HeimrichHannot\MultiFileUploadBundle\:
    resource: '../../{EventListener}/*'
    autoconfigure: true

  HeimrichHannot\MultiFileUploadBundle\Asset\FrontendAsset:
    public: true
    calls:
      - [ setEncoreFrontendAsset, [ '@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset' ] ]