services:
  _defaults:
    autowire: true

  HeimrichHannot\MultiFileUploadBundle\:
    resource: '../../{Asset,EventListener,File}/*'
    autoconfigure: true
    bind:
      $logger: '@monolog.logger.contao'

  HeimrichHannot\MultiFileUploadBundle\Asset\FrontendAsset:
    public: true
    autoconfigure: true

  HeimrichHannot\MultiFileUploadBundle\File\FilesHandler:
    autowire: true
    public: true

  HeimrichHannot\MultiFileUploadBundle\EventListener\Callback\OnSubmitCallbackListener:
    autowire: true
    public: true