services:
  _defaults:
    autowire: true

  HeimrichHannot\MultiFileUploadBundle\:
    resource: '../../{Asset,EventListener}/*'
    autoconfigure: true
    bind:
      $logger: '@monolog.logger.contao'

  HeimrichHannot\MultiFileUploadBundle\Asset\FrontendAsset:
    public: true
    autoconfigure: true