services:
    _defaults:
        autowire: true

    HeimrichHannot\MultiFileUploadBundle\Asset\FrontendAsset:
        public: true
        calls:
            - [setEncoreFrontendAsset, ['@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset']]

    huh.multifileupload.listener.hooks:
        class: HeimrichHannot\MultiFileUploadBundle\EventListener\HookListener
        public: true