services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $logger: "@monolog.logger.contao"

  HeimrichHannot\MultiFileUploadBundle\Asset\FrontendAsset:
    public: true
    calls:
      - [ setEncoreFrontendAsset, [ '@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset' ] ]

  HeimrichHannot\MultiFileUploadBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    public: true